#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCheck
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="drillthrall")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdata_dictionary(data_dictionary instance);
    partial void Updatedata_dictionary(data_dictionary instance);
    partial void Deletedata_dictionary(data_dictionary instance);
    partial void Insertdata_drill_dictionary(data_drill_dictionary instance);
    partial void Updatedata_drill_dictionary(data_drill_dictionary instance);
    partial void Deletedata_drill_dictionary(data_drill_dictionary instance);
    partial void Insertdata_drill(data_drill instance);
    partial void Updatedata_drill(data_drill instance);
    partial void Deletedata_drill(data_drill instance);
    partial void Insertdata_english2steno(data_english2steno instance);
    partial void Updatedata_english2steno(data_english2steno instance);
    partial void Deletedata_english2steno(data_english2steno instance);
    partial void Insertdata_englishsentence2steno(data_englishsentence2steno instance);
    partial void Updatedata_englishsentence2steno(data_englishsentence2steno instance);
    partial void Deletedata_englishsentence2steno(data_englishsentence2steno instance);
    partial void Insertdata_sentencedrill(data_sentencedrill instance);
    partial void Updatedata_sentencedrill(data_sentencedrill instance);
    partial void Deletedata_sentencedrill(data_sentencedrill instance);
    partial void Insertdata_sentencedrills_sentence(data_sentencedrills_sentence instance);
    partial void Updatedata_sentencedrills_sentence(data_sentencedrills_sentence instance);
    partial void Deletedata_sentencedrills_sentence(data_sentencedrills_sentence instance);
    partial void Insertdata_sentence(data_sentence instance);
    partial void Updatedata_sentence(data_sentence instance);
    partial void Deletedata_sentence(data_sentence instance);
    partial void Insertdata_steno2english(data_steno2english instance);
    partial void Updatedata_steno2english(data_steno2english instance);
    partial void Deletedata_steno2english(data_steno2english instance);
    partial void Insertdata_wordconfusion(data_wordconfusion instance);
    partial void Updatedata_wordconfusion(data_wordconfusion instance);
    partial void Deletedata_wordconfusion(data_wordconfusion instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WordCheck.Properties.Settings.Default.drillthrallConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<data_dictionary> data_dictionaries
		{
			get
			{
				return this.GetTable<data_dictionary>();
			}
		}
		
		public System.Data.Linq.Table<data_drill_dictionary> data_drill_dictionaries
		{
			get
			{
				return this.GetTable<data_drill_dictionary>();
			}
		}
		
		public System.Data.Linq.Table<data_drill> data_drills
		{
			get
			{
				return this.GetTable<data_drill>();
			}
		}
		
		public System.Data.Linq.Table<data_english2steno> data_english2stenos
		{
			get
			{
				return this.GetTable<data_english2steno>();
			}
		}
		
		public System.Data.Linq.Table<data_englishsentence2steno> data_englishsentence2stenos
		{
			get
			{
				return this.GetTable<data_englishsentence2steno>();
			}
		}
		
		public System.Data.Linq.Table<data_sentencedrill> data_sentencedrills
		{
			get
			{
				return this.GetTable<data_sentencedrill>();
			}
		}
		
		public System.Data.Linq.Table<data_sentencedrills_sentence> data_sentencedrills_sentences
		{
			get
			{
				return this.GetTable<data_sentencedrills_sentence>();
			}
		}
		
		public System.Data.Linq.Table<data_sentence> data_sentences
		{
			get
			{
				return this.GetTable<data_sentence>();
			}
		}
		
		public System.Data.Linq.Table<data_steno2english> data_steno2englishes
		{
			get
			{
				return this.GetTable<data_steno2english>();
			}
		}
		
		public System.Data.Linq.Table<data_wordconfusion> data_wordconfusions
		{
			get
			{
				return this.GetTable<data_wordconfusion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_AddMistakeRecord")]
		public int pr_AddMistakeRecord([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> wordid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string incorrectword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), wordid, incorrectword);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_dictionary")]
	public partial class data_dictionary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _steno;
		
		private string _english;
		
		private EntitySet<data_drill_dictionary> _data_drill_dictionaries;
		
		private EntitySet<data_english2steno> _data_english2stenos;
		
		private EntitySet<data_steno2english> _data_steno2englishes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnstenoChanging(string value);
    partial void OnstenoChanged();
    partial void OnenglishChanging(string value);
    partial void OnenglishChanged();
    #endregion
		
		public data_dictionary()
		{
			this._data_drill_dictionaries = new EntitySet<data_drill_dictionary>(new Action<data_drill_dictionary>(this.attach_data_drill_dictionaries), new Action<data_drill_dictionary>(this.detach_data_drill_dictionaries));
			this._data_english2stenos = new EntitySet<data_english2steno>(new Action<data_english2steno>(this.attach_data_english2stenos), new Action<data_english2steno>(this.detach_data_english2stenos));
			this._data_steno2englishes = new EntitySet<data_steno2english>(new Action<data_steno2english>(this.attach_data_steno2englishes), new Action<data_steno2english>(this.detach_data_steno2englishes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_steno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string steno
		{
			get
			{
				return this._steno;
			}
			set
			{
				if ((this._steno != value))
				{
					this.OnstenoChanging(value);
					this.SendPropertyChanging();
					this._steno = value;
					this.SendPropertyChanged("steno");
					this.OnstenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_english", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string english
		{
			get
			{
				return this._english;
			}
			set
			{
				if ((this._english != value))
				{
					this.OnenglishChanging(value);
					this.SendPropertyChanging();
					this._english = value;
					this.SendPropertyChanged("english");
					this.OnenglishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_dictionary_data_drill_dictionary", Storage="_data_drill_dictionaries", ThisKey="id", OtherKey="dictionaryid")]
		public EntitySet<data_drill_dictionary> data_drill_dictionaries
		{
			get
			{
				return this._data_drill_dictionaries;
			}
			set
			{
				this._data_drill_dictionaries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_dictionary_data_english2steno", Storage="_data_english2stenos", ThisKey="id", OtherKey="dictionaryid")]
		public EntitySet<data_english2steno> data_english2stenos
		{
			get
			{
				return this._data_english2stenos;
			}
			set
			{
				this._data_english2stenos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_dictionary_data_steno2english", Storage="_data_steno2englishes", ThisKey="id", OtherKey="dictionaryid")]
		public EntitySet<data_steno2english> data_steno2englishes
		{
			get
			{
				return this._data_steno2englishes;
			}
			set
			{
				this._data_steno2englishes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_data_drill_dictionaries(data_drill_dictionary entity)
		{
			this.SendPropertyChanging();
			entity.data_dictionary = this;
		}
		
		private void detach_data_drill_dictionaries(data_drill_dictionary entity)
		{
			this.SendPropertyChanging();
			entity.data_dictionary = null;
		}
		
		private void attach_data_english2stenos(data_english2steno entity)
		{
			this.SendPropertyChanging();
			entity.data_dictionary = this;
		}
		
		private void detach_data_english2stenos(data_english2steno entity)
		{
			this.SendPropertyChanging();
			entity.data_dictionary = null;
		}
		
		private void attach_data_steno2englishes(data_steno2english entity)
		{
			this.SendPropertyChanging();
			entity.data_dictionary = this;
		}
		
		private void detach_data_steno2englishes(data_steno2english entity)
		{
			this.SendPropertyChanging();
			entity.data_dictionary = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_drill_dictionary")]
	public partial class data_drill_dictionary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _drillid;
		
		private long _dictionaryid;
		
		private EntityRef<data_dictionary> _data_dictionary;
		
		private EntityRef<data_drill> _data_drill;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OndrillidChanging(long value);
    partial void OndrillidChanged();
    partial void OndictionaryidChanging(long value);
    partial void OndictionaryidChanged();
    #endregion
		
		public data_drill_dictionary()
		{
			this._data_dictionary = default(EntityRef<data_dictionary>);
			this._data_drill = default(EntityRef<data_drill>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drillid", DbType="BigInt NOT NULL")]
		public long drillid
		{
			get
			{
				return this._drillid;
			}
			set
			{
				if ((this._drillid != value))
				{
					if (this._data_drill.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndrillidChanging(value);
					this.SendPropertyChanging();
					this._drillid = value;
					this.SendPropertyChanged("drillid");
					this.OndrillidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dictionaryid", DbType="BigInt NOT NULL")]
		public long dictionaryid
		{
			get
			{
				return this._dictionaryid;
			}
			set
			{
				if ((this._dictionaryid != value))
				{
					if (this._data_dictionary.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndictionaryidChanging(value);
					this.SendPropertyChanging();
					this._dictionaryid = value;
					this.SendPropertyChanged("dictionaryid");
					this.OndictionaryidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_dictionary_data_drill_dictionary", Storage="_data_dictionary", ThisKey="dictionaryid", OtherKey="id", IsForeignKey=true)]
		public data_dictionary data_dictionary
		{
			get
			{
				return this._data_dictionary.Entity;
			}
			set
			{
				data_dictionary previousValue = this._data_dictionary.Entity;
				if (((previousValue != value) 
							|| (this._data_dictionary.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_dictionary.Entity = null;
						previousValue.data_drill_dictionaries.Remove(this);
					}
					this._data_dictionary.Entity = value;
					if ((value != null))
					{
						value.data_drill_dictionaries.Add(this);
						this._dictionaryid = value.id;
					}
					else
					{
						this._dictionaryid = default(long);
					}
					this.SendPropertyChanged("data_dictionary");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_drill_data_drill_dictionary", Storage="_data_drill", ThisKey="drillid", OtherKey="id", IsForeignKey=true)]
		public data_drill data_drill
		{
			get
			{
				return this._data_drill.Entity;
			}
			set
			{
				data_drill previousValue = this._data_drill.Entity;
				if (((previousValue != value) 
							|| (this._data_drill.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_drill.Entity = null;
						previousValue.data_drill_dictionaries.Remove(this);
					}
					this._data_drill.Entity = value;
					if ((value != null))
					{
						value.data_drill_dictionaries.Add(this);
						this._drillid = value.id;
					}
					else
					{
						this._drillid = default(long);
					}
					this.SendPropertyChanged("data_drill");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_drills")]
	public partial class data_drill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _drillname;
		
		private EntitySet<data_drill_dictionary> _data_drill_dictionaries;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OndrillnameChanging(string value);
    partial void OndrillnameChanged();
    #endregion
		
		public data_drill()
		{
			this._data_drill_dictionaries = new EntitySet<data_drill_dictionary>(new Action<data_drill_dictionary>(this.attach_data_drill_dictionaries), new Action<data_drill_dictionary>(this.detach_data_drill_dictionaries));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drillname", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string drillname
		{
			get
			{
				return this._drillname;
			}
			set
			{
				if ((this._drillname != value))
				{
					this.OndrillnameChanging(value);
					this.SendPropertyChanging();
					this._drillname = value;
					this.SendPropertyChanged("drillname");
					this.OndrillnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_drill_data_drill_dictionary", Storage="_data_drill_dictionaries", ThisKey="id", OtherKey="drillid")]
		public EntitySet<data_drill_dictionary> data_drill_dictionaries
		{
			get
			{
				return this._data_drill_dictionaries;
			}
			set
			{
				this._data_drill_dictionaries.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_data_drill_dictionaries(data_drill_dictionary entity)
		{
			this.SendPropertyChanging();
			entity.data_drill = this;
		}
		
		private void detach_data_drill_dictionaries(data_drill_dictionary entity)
		{
			this.SendPropertyChanging();
			entity.data_drill = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_english2steno")]
	public partial class data_english2steno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _dictionaryid;
		
		private System.DateTime _testtime;
		
		private int _msspeed;
		
		private string _misspell;
		
		private EntityRef<data_dictionary> _data_dictionary;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OndictionaryidChanging(long value);
    partial void OndictionaryidChanged();
    partial void OntesttimeChanging(System.DateTime value);
    partial void OntesttimeChanged();
    partial void OnmsspeedChanging(int value);
    partial void OnmsspeedChanged();
    partial void OnmisspellChanging(string value);
    partial void OnmisspellChanged();
    #endregion
		
		public data_english2steno()
		{
			this._data_dictionary = default(EntityRef<data_dictionary>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dictionaryid", DbType="BigInt NOT NULL")]
		public long dictionaryid
		{
			get
			{
				return this._dictionaryid;
			}
			set
			{
				if ((this._dictionaryid != value))
				{
					if (this._data_dictionary.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndictionaryidChanging(value);
					this.SendPropertyChanging();
					this._dictionaryid = value;
					this.SendPropertyChanged("dictionaryid");
					this.OndictionaryidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testtime", DbType="DateTime NOT NULL")]
		public System.DateTime testtime
		{
			get
			{
				return this._testtime;
			}
			set
			{
				if ((this._testtime != value))
				{
					this.OntesttimeChanging(value);
					this.SendPropertyChanging();
					this._testtime = value;
					this.SendPropertyChanged("testtime");
					this.OntesttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msspeed", DbType="Int NOT NULL")]
		public int msspeed
		{
			get
			{
				return this._msspeed;
			}
			set
			{
				if ((this._msspeed != value))
				{
					this.OnmsspeedChanging(value);
					this.SendPropertyChanging();
					this._msspeed = value;
					this.SendPropertyChanged("msspeed");
					this.OnmsspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_misspell", DbType="VarChar(50)")]
		public string misspell
		{
			get
			{
				return this._misspell;
			}
			set
			{
				if ((this._misspell != value))
				{
					this.OnmisspellChanging(value);
					this.SendPropertyChanging();
					this._misspell = value;
					this.SendPropertyChanged("misspell");
					this.OnmisspellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_dictionary_data_english2steno", Storage="_data_dictionary", ThisKey="dictionaryid", OtherKey="id", IsForeignKey=true)]
		public data_dictionary data_dictionary
		{
			get
			{
				return this._data_dictionary.Entity;
			}
			set
			{
				data_dictionary previousValue = this._data_dictionary.Entity;
				if (((previousValue != value) 
							|| (this._data_dictionary.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_dictionary.Entity = null;
						previousValue.data_english2stenos.Remove(this);
					}
					this._data_dictionary.Entity = value;
					if ((value != null))
					{
						value.data_english2stenos.Add(this);
						this._dictionaryid = value.id;
					}
					else
					{
						this._dictionaryid = default(long);
					}
					this.SendPropertyChanged("data_dictionary");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_englishsentence2steno")]
	public partial class data_englishsentence2steno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _sentenceid;
		
		private System.DateTime _testtime;
		
		private int _msspeed;
		
		private EntityRef<data_sentence> _data_sentence;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnsentenceidChanging(long value);
    partial void OnsentenceidChanged();
    partial void OntesttimeChanging(System.DateTime value);
    partial void OntesttimeChanged();
    partial void OnmsspeedChanging(int value);
    partial void OnmsspeedChanged();
    #endregion
		
		public data_englishsentence2steno()
		{
			this._data_sentence = default(EntityRef<data_sentence>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sentenceid", DbType="BigInt NOT NULL")]
		public long sentenceid
		{
			get
			{
				return this._sentenceid;
			}
			set
			{
				if ((this._sentenceid != value))
				{
					if (this._data_sentence.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsentenceidChanging(value);
					this.SendPropertyChanging();
					this._sentenceid = value;
					this.SendPropertyChanged("sentenceid");
					this.OnsentenceidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testtime", DbType="DateTime NOT NULL")]
		public System.DateTime testtime
		{
			get
			{
				return this._testtime;
			}
			set
			{
				if ((this._testtime != value))
				{
					this.OntesttimeChanging(value);
					this.SendPropertyChanging();
					this._testtime = value;
					this.SendPropertyChanged("testtime");
					this.OntesttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msspeed", DbType="Int NOT NULL")]
		public int msspeed
		{
			get
			{
				return this._msspeed;
			}
			set
			{
				if ((this._msspeed != value))
				{
					this.OnmsspeedChanging(value);
					this.SendPropertyChanging();
					this._msspeed = value;
					this.SendPropertyChanged("msspeed");
					this.OnmsspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_sentence_data_englishsentence2steno", Storage="_data_sentence", ThisKey="sentenceid", OtherKey="id", IsForeignKey=true)]
		public data_sentence data_sentence
		{
			get
			{
				return this._data_sentence.Entity;
			}
			set
			{
				data_sentence previousValue = this._data_sentence.Entity;
				if (((previousValue != value) 
							|| (this._data_sentence.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_sentence.Entity = null;
						previousValue.data_englishsentence2stenos.Remove(this);
					}
					this._data_sentence.Entity = value;
					if ((value != null))
					{
						value.data_englishsentence2stenos.Add(this);
						this._sentenceid = value.id;
					}
					else
					{
						this._sentenceid = default(long);
					}
					this.SendPropertyChanged("data_sentence");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_sentencedrills")]
	public partial class data_sentencedrill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _drillname;
		
		private EntitySet<data_sentencedrills_sentence> _data_sentencedrills_sentences;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OndrillnameChanging(string value);
    partial void OndrillnameChanged();
    #endregion
		
		public data_sentencedrill()
		{
			this._data_sentencedrills_sentences = new EntitySet<data_sentencedrills_sentence>(new Action<data_sentencedrills_sentence>(this.attach_data_sentencedrills_sentences), new Action<data_sentencedrills_sentence>(this.detach_data_sentencedrills_sentences));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drillname", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string drillname
		{
			get
			{
				return this._drillname;
			}
			set
			{
				if ((this._drillname != value))
				{
					this.OndrillnameChanging(value);
					this.SendPropertyChanging();
					this._drillname = value;
					this.SendPropertyChanged("drillname");
					this.OndrillnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_sentencedrill_data_sentencedrills_sentence", Storage="_data_sentencedrills_sentences", ThisKey="id", OtherKey="sentencedrillid")]
		public EntitySet<data_sentencedrills_sentence> data_sentencedrills_sentences
		{
			get
			{
				return this._data_sentencedrills_sentences;
			}
			set
			{
				this._data_sentencedrills_sentences.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_data_sentencedrills_sentences(data_sentencedrills_sentence entity)
		{
			this.SendPropertyChanging();
			entity.data_sentencedrill = this;
		}
		
		private void detach_data_sentencedrills_sentences(data_sentencedrills_sentence entity)
		{
			this.SendPropertyChanging();
			entity.data_sentencedrill = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_sentencedrills_sentences")]
	public partial class data_sentencedrills_sentence : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _sentencedrillid;
		
		private long _sentenceid;
		
		private EntityRef<data_sentencedrill> _data_sentencedrill;
		
		private EntityRef<data_sentence> _data_sentence;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnsentencedrillidChanging(long value);
    partial void OnsentencedrillidChanged();
    partial void OnsentenceidChanging(long value);
    partial void OnsentenceidChanged();
    #endregion
		
		public data_sentencedrills_sentence()
		{
			this._data_sentencedrill = default(EntityRef<data_sentencedrill>);
			this._data_sentence = default(EntityRef<data_sentence>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sentencedrillid", DbType="BigInt NOT NULL")]
		public long sentencedrillid
		{
			get
			{
				return this._sentencedrillid;
			}
			set
			{
				if ((this._sentencedrillid != value))
				{
					if (this._data_sentencedrill.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsentencedrillidChanging(value);
					this.SendPropertyChanging();
					this._sentencedrillid = value;
					this.SendPropertyChanged("sentencedrillid");
					this.OnsentencedrillidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sentenceid", DbType="BigInt NOT NULL")]
		public long sentenceid
		{
			get
			{
				return this._sentenceid;
			}
			set
			{
				if ((this._sentenceid != value))
				{
					if (this._data_sentence.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsentenceidChanging(value);
					this.SendPropertyChanging();
					this._sentenceid = value;
					this.SendPropertyChanged("sentenceid");
					this.OnsentenceidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_sentencedrill_data_sentencedrills_sentence", Storage="_data_sentencedrill", ThisKey="sentencedrillid", OtherKey="id", IsForeignKey=true)]
		public data_sentencedrill data_sentencedrill
		{
			get
			{
				return this._data_sentencedrill.Entity;
			}
			set
			{
				data_sentencedrill previousValue = this._data_sentencedrill.Entity;
				if (((previousValue != value) 
							|| (this._data_sentencedrill.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_sentencedrill.Entity = null;
						previousValue.data_sentencedrills_sentences.Remove(this);
					}
					this._data_sentencedrill.Entity = value;
					if ((value != null))
					{
						value.data_sentencedrills_sentences.Add(this);
						this._sentencedrillid = value.id;
					}
					else
					{
						this._sentencedrillid = default(long);
					}
					this.SendPropertyChanged("data_sentencedrill");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_sentence_data_sentencedrills_sentence", Storage="_data_sentence", ThisKey="sentenceid", OtherKey="id", IsForeignKey=true)]
		public data_sentence data_sentence
		{
			get
			{
				return this._data_sentence.Entity;
			}
			set
			{
				data_sentence previousValue = this._data_sentence.Entity;
				if (((previousValue != value) 
							|| (this._data_sentence.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_sentence.Entity = null;
						previousValue.data_sentencedrills_sentences.Remove(this);
					}
					this._data_sentence.Entity = value;
					if ((value != null))
					{
						value.data_sentencedrills_sentences.Add(this);
						this._sentenceid = value.id;
					}
					else
					{
						this._sentenceid = default(long);
					}
					this.SendPropertyChanged("data_sentence");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_sentences")]
	public partial class data_sentence : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _sentence;
		
		private EntitySet<data_englishsentence2steno> _data_englishsentence2stenos;
		
		private EntitySet<data_sentencedrills_sentence> _data_sentencedrills_sentences;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnsentenceChanging(string value);
    partial void OnsentenceChanged();
    #endregion
		
		public data_sentence()
		{
			this._data_englishsentence2stenos = new EntitySet<data_englishsentence2steno>(new Action<data_englishsentence2steno>(this.attach_data_englishsentence2stenos), new Action<data_englishsentence2steno>(this.detach_data_englishsentence2stenos));
			this._data_sentencedrills_sentences = new EntitySet<data_sentencedrills_sentence>(new Action<data_sentencedrills_sentence>(this.attach_data_sentencedrills_sentences), new Action<data_sentencedrills_sentence>(this.detach_data_sentencedrills_sentences));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sentence", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sentence
		{
			get
			{
				return this._sentence;
			}
			set
			{
				if ((this._sentence != value))
				{
					this.OnsentenceChanging(value);
					this.SendPropertyChanging();
					this._sentence = value;
					this.SendPropertyChanged("sentence");
					this.OnsentenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_sentence_data_englishsentence2steno", Storage="_data_englishsentence2stenos", ThisKey="id", OtherKey="sentenceid")]
		public EntitySet<data_englishsentence2steno> data_englishsentence2stenos
		{
			get
			{
				return this._data_englishsentence2stenos;
			}
			set
			{
				this._data_englishsentence2stenos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_sentence_data_sentencedrills_sentence", Storage="_data_sentencedrills_sentences", ThisKey="id", OtherKey="sentenceid")]
		public EntitySet<data_sentencedrills_sentence> data_sentencedrills_sentences
		{
			get
			{
				return this._data_sentencedrills_sentences;
			}
			set
			{
				this._data_sentencedrills_sentences.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_data_englishsentence2stenos(data_englishsentence2steno entity)
		{
			this.SendPropertyChanging();
			entity.data_sentence = this;
		}
		
		private void detach_data_englishsentence2stenos(data_englishsentence2steno entity)
		{
			this.SendPropertyChanging();
			entity.data_sentence = null;
		}
		
		private void attach_data_sentencedrills_sentences(data_sentencedrills_sentence entity)
		{
			this.SendPropertyChanging();
			entity.data_sentence = this;
		}
		
		private void detach_data_sentencedrills_sentences(data_sentencedrills_sentence entity)
		{
			this.SendPropertyChanging();
			entity.data_sentence = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_steno2english")]
	public partial class data_steno2english : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _dictionaryid;
		
		private System.DateTime _testtime;
		
		private int _msspeed;
		
		private string _misspell;
		
		private EntityRef<data_dictionary> _data_dictionary;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OndictionaryidChanging(long value);
    partial void OndictionaryidChanged();
    partial void OntesttimeChanging(System.DateTime value);
    partial void OntesttimeChanged();
    partial void OnmsspeedChanging(int value);
    partial void OnmsspeedChanged();
    partial void OnmisspellChanging(string value);
    partial void OnmisspellChanged();
    #endregion
		
		public data_steno2english()
		{
			this._data_dictionary = default(EntityRef<data_dictionary>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dictionaryid", DbType="BigInt NOT NULL")]
		public long dictionaryid
		{
			get
			{
				return this._dictionaryid;
			}
			set
			{
				if ((this._dictionaryid != value))
				{
					if (this._data_dictionary.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndictionaryidChanging(value);
					this.SendPropertyChanging();
					this._dictionaryid = value;
					this.SendPropertyChanged("dictionaryid");
					this.OndictionaryidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testtime", DbType="DateTime NOT NULL")]
		public System.DateTime testtime
		{
			get
			{
				return this._testtime;
			}
			set
			{
				if ((this._testtime != value))
				{
					this.OntesttimeChanging(value);
					this.SendPropertyChanging();
					this._testtime = value;
					this.SendPropertyChanged("testtime");
					this.OntesttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msspeed", DbType="Int NOT NULL")]
		public int msspeed
		{
			get
			{
				return this._msspeed;
			}
			set
			{
				if ((this._msspeed != value))
				{
					this.OnmsspeedChanging(value);
					this.SendPropertyChanging();
					this._msspeed = value;
					this.SendPropertyChanged("msspeed");
					this.OnmsspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_misspell", DbType="VarChar(100)")]
		public string misspell
		{
			get
			{
				return this._misspell;
			}
			set
			{
				if ((this._misspell != value))
				{
					this.OnmisspellChanging(value);
					this.SendPropertyChanging();
					this._misspell = value;
					this.SendPropertyChanged("misspell");
					this.OnmisspellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_dictionary_data_steno2english", Storage="_data_dictionary", ThisKey="dictionaryid", OtherKey="id", IsForeignKey=true)]
		public data_dictionary data_dictionary
		{
			get
			{
				return this._data_dictionary.Entity;
			}
			set
			{
				data_dictionary previousValue = this._data_dictionary.Entity;
				if (((previousValue != value) 
							|| (this._data_dictionary.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_dictionary.Entity = null;
						previousValue.data_steno2englishes.Remove(this);
					}
					this._data_dictionary.Entity = value;
					if ((value != null))
					{
						value.data_steno2englishes.Add(this);
						this._dictionaryid = value.id;
					}
					else
					{
						this._dictionaryid = default(long);
					}
					this.SendPropertyChanged("data_dictionary");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_wordconfusions")]
	public partial class data_wordconfusion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _wordid;
		
		private string _incorrectword;
		
		private System.DateTime _incorrectdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnwordidChanging(long value);
    partial void OnwordidChanged();
    partial void OnincorrectwordChanging(string value);
    partial void OnincorrectwordChanged();
    partial void OnincorrectdateChanging(System.DateTime value);
    partial void OnincorrectdateChanged();
    #endregion
		
		public data_wordconfusion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wordid", DbType="BigInt NOT NULL")]
		public long wordid
		{
			get
			{
				return this._wordid;
			}
			set
			{
				if ((this._wordid != value))
				{
					this.OnwordidChanging(value);
					this.SendPropertyChanging();
					this._wordid = value;
					this.SendPropertyChanged("wordid");
					this.OnwordidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_incorrectword", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string incorrectword
		{
			get
			{
				return this._incorrectword;
			}
			set
			{
				if ((this._incorrectword != value))
				{
					this.OnincorrectwordChanging(value);
					this.SendPropertyChanging();
					this._incorrectword = value;
					this.SendPropertyChanged("incorrectword");
					this.OnincorrectwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_incorrectdate", DbType="DateTime NOT NULL")]
		public System.DateTime incorrectdate
		{
			get
			{
				return this._incorrectdate;
			}
			set
			{
				if ((this._incorrectdate != value))
				{
					this.OnincorrectdateChanging(value);
					this.SendPropertyChanging();
					this._incorrectdate = value;
					this.SendPropertyChanged("incorrectdate");
					this.OnincorrectdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
