using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WordCheck
{
    public partial class Form1 : Form
    {
        private DateTime timeStart;
        private DateTime timeEnd;
        Boolean match = false;
        int mistakes = 0;

        public Form1()
        {
            InitializeComponent();

            timer1.Interval = 10;


            timer1.Tick += Timer_Tick;

            // start things
            //label1.Hide();
            //button1.Hide();
            //timer1.Start();

            //listBox1.HorizontalScrollbar = true;
            //listBox1.FormattingEnabled = true;
            //listBox1.ScrollAlwaysVisible = true;
            //listBox1.TabIndex = 0;
            //listBox1.ColumnWidth = 85;
            //listBox1.MultiColumn = true;


        }

        private void button1_Click(object sender, EventArgs e)
        {
            timeStart = DateTime.Now;
            textBox1.Focus();

            //            List<string> words = new List<string>{ "I am",
            //"I had",
            //"I have",
            //"I will",
            //"I would",
            //"I'd",
            //"I didn't say",
            //"I'll",
            //"I'm",
            //"I've",
            //"aren't",
            //"can't",
            //"couldn't",
            //"didn't",
            //"don't",
            //"doesn't",
            //"hadn't",
            //"hasn't",
            //"weren't",
            //"won't",
            //"wouldn't",
            //"ease",
            //"haven't",
            //"he had",
            //"he is",
            //"he see",
            //"he will",
            //"he would",
            //"he'd",
            //"he'll",
            //"he's",
            //"head",
            //"heal",
            //"heed",
            //"held",
            //"isn't",
            //"it had",
            //"it is",
            //"it see",
            //"it will",
            //"it would",
            //"it'd",
            //"it'll",
            //"it's",
            //"its",
            //"let us",
            //"let's",
            //"she had",
            //"she is",
            //"she see",
            //"she will",
            //"she would",
            //"she'd",
            //"she'll",
            //"she's",
            //"shell",
            //"shouldn't",
            //"that had",
            //"that is",
            //"that will",
            //"that'd",
            //"that'll",
            //"that's",
            //"there had",
            //"there is",
            //"there will",
            //"there'll",
            //"there's",
            //"they are",
            //"they had",
            //"they will",
            //"they would",
            //"they'd",
            //"they'll",
            //"they're",
            //"wasn't",
            //"who are",
            //"who had",
            //"who have",
            //"who is",
            //"who will",
            //"who'd",
            //"who'll",
            //"who're",
            //"who's",
            //"who've",
            //"why is",
            //"why's",
            //"you are",
            //"you had",
            //"you have",
            //"you will",
            //"you would",
            //"you'd",
            //"you'll",
            //"you're",
            //"you've" };

            //            List<string> words = new List<string>
            //            { "a",
            //"about",
            //"accept",
            //"against",
            //"all",
            //"amount",
            //"and",
            //"anyone",
            //"anything",
            //"apology",
            //"appreciate",
            //"are",
            //"as",
            //"ask",
            //"asked",
            //"assistant",
            //"assumption",
            //"at",
            //"attorney",
            //"background",
            //"be",
            //"because",
            //"been",
            //"before",
            //"behalf",
            //"behind",
            //"believe",
            //"beyond",
            //"but",
            //"by",
            //"calculation",
            //"certainly",
            //"charge",
            //"charges",
            //"city",
            //"clear",
            //"community",
            //"conclude",
            //"consideration",
            //"conversation",
            //"conversations",
            //"copied",
            //"copies",
            //"county",
            //"courthouse",
            //"damage",
            //"damages",
            //"day",
            //"decide",
            //"decided",
            //"decision",
            //"department",
            //"do",
            //"doing",
            //"done",
            //"doubt",
            //"during",
            //"earlier",
            //"estimate",
            //"evidence",
            //"facts",
            //"file",
            //"finance",
            //"financial",
            //"for",
            //"forward",
            //"frequent",
            //"gave",
            //"glad",
            //"go",
            //"going",
            //"gone",
            //"good",
            //"got",
            //"govern",
            //"government",
            //"great",
            //"guess",
            //"guilt",
            //"guilty",
            //"had",
            //"has",
            //"have",
            //"her",
            //"here",
            //"he'd",
            //"he'll",
            //"he's",
            //"hope",
            //"however",
            //"I",
            //"if",
            //"in",
            //"include",
            //"income",
            //"initial",
            //"innocence",
            //"innocent",
            //"into",
            //"introduce",
            //"introduction",
            //"is",
            //"it",
            //"it'd",
            //"it'll",
            //"it's",
            //"I'd",
            //"I'll",
            //"I'm",
            //"I've",
            //"January",
            //"just",
            //"last",
            //"lawsuit",
            //"learned",
            //"least",
            //"lesson",
            //"like",
            //"longer",
            //"lost",
            //"lot",
            //"made",
            //"make",
            //"me",
            //"month",
            //"Mrs.",
            //"my",
            //"never",
            //"new",
            //"newspaper",
            //"no",
            //"not",
            //"notice",
            //"now",
            //"of",
            //"official",
            //"on",
            //"one",
            //"opinion",
            //"or",
            //"over",
            //"papers",
            //"part",
            //"place",
            //"please",
            //"pleasure",
            //"printers",
            //"probably",
            //"procedure",
            //"program",
            //"prove",
            //"provided",
            //"put",
            //"reach",
            //"ready",
            //"reasonable",
            //"regarding",
            //"remain",
            //"replace",
            //"reputation",
            //"rules",
            //"said",
            //"saved",
            //"say",
            //"secretary",
            //"seen",
            //"she",
            //"she'd",
            //"she'll",
            //"she's",
            //"signing",
            //"since",
            //"sir",
            //"soon",
            //"spoken",
            //"stay",
            //"sure",
            //"take",
            //"taken",
            //"tarnished",
            //"tell",
            //"that",
            //"that'd",
            //"that'll",
            //"that's",
            //"the",
            //"them",
            //"there",
            //"thereafter",
            //"there'll",
            //"there's",
            //"these",
            //"they'd",
            //"they'll",
            //"they're",
            //"they've",
            //"thing",
            //"think",
            //"this",
            //"those",
            //"time",
            //"to",
            //"together",
            //"trip",
            //"what's",
            //"well",
            //"we'd",
            //"we're",
            //"we've",
            //"what",
            //"what's",
            //"when's",
            //"who'd",
            //"who'll",
            //"who're",
            //"who's",
            //"who've",
            //"with",
            //"working",
            //"would",
            //"years",
            //"you",
            //"your",
            //"you'd",
            //"you'll",
            //"you're",
            //"you've"
            //};

            List<string> words = new List<string>
            {
"absolute",
"absolutely",
"amend",
"amendment",
"america",
"american",
"appreciate",
"appreciation",
"associate",
"association",
"build",
"builder",
"built",
"buy",
"bye",
"captain",
"careful",
"coast",
"company",
"confidence",
"confident",
"conference",
"corroborate",
"credible",
"credibility",
"defense",
"deny",
"denial",
"describe",
"description",
"determine",
"develop",
"development",
"diagnose",
"diagnoses",
"diagnosis",
"diagnostic",
"discuss",
"discussion",
"document",
"during",
"employ",
"employee",
"employer",
"employment",
"enable",
"energy",
"equipment",
"establish",
"establishment",
"even",
"exam",
"examine",
"general",
"general",
"good",
"goodbye",
"headache",
"help",
"hospital",
"imagine",
"indict",
"indictment",
"individual",
"industry",
"industrial",
"industrialization",
"insurance",
"insure",
"insured",
"insurer",
"interest",
"investigate",
"investigation",
"involve",
"involvement",
"issue",
"jr.",
"junior",
"judgment",
"lawyer",
"license",
"m.d.",
"major",
"majority",
"manage",
"manager",
"management",
"manufacture",
"manufacturer",
"marry",
"marriage",
"medical",
"member",
"miss",
"money",
"mountain",
"ms.",
"nature",
"necessary",
"necessarily",
"necessity",
"new",
"o'clock",
"occasion",
"occupation",
"once",
"ones",
"operate",
"operation",
"opinion",
"option",
"paper",
"part-time",
"party",
"patient",
"permanent",
"permit",
"petition",
"photograph",
"photographer",
"photographic",
"physical",
"physician",
"possible",
"possibly",
"position",
"preliminary",
"prescribe",
"presence",
"present",
"prescription",
"president",
"produce",
"product",
"production",
"profit",
"railroad",
"recommend",
"recognize",
"regular",
"remember",
"represent",
"require",
"responsible",
"responsibility",
"season",
"second",
"secretary",
"senior",
"sergeant",
"shipment",
"sidewalk",
"signal",
"significance",
"significant",
"society",
"sr.",
"statement",
"student",
"suggest",
"suggestion",
"summon",
"superintendent",
"threw",
"treatment",
"unable",
"united states",
"value",
"vice-president",
"within",
"without",
"witness"
 };


            //            List<string> words = new List<string>
            //            {
            //"aren't",
            //"can't",
            //"couldn't",
            //"didn't",
            //"don't",
            //"doesn't",
            //"hadn't",
            //"hasn't",
            //"haven't",
            //"isn't",
            //"shouldn't",
            //"wasn't",
            //"weren't",
            //"won't",
            //"wouldn't",
            //"I will",
            //"you will",
            //"he will",
            //"she will",
            //"they will",
            //"it will",
            //"that will",
            //"there will",
            //"who will",
            //"I'll",
            //"you'll",
            //"he'll",
            //"she'll",
            //"they'll",
            //"it'll",
            //"that'll",
            //"there'll",
            //"who'll",
            //"I would",
            //"you would",
            //"he would",
            //"she would",
            //"they would",
            //"it would",
            //"that would",
            //"who would",
            //"I had",
            //"you had",
            //"he had",
            //"she had",
            //"they had",
            //"it had",
            //"that had",
            //"who had",
            //"I have",
            //"you have",
            //"they have",
            //"we have",
            //"who have",
            //"we are",
            //"they are",
            //"who are",
            //"you are",
            //"he is",
            //"she is",
            //"it is",
            //"that is",
            //"there is",
            //"what is",
            //"I'd",
            //"you'd",
            //"he'd",
            //"she'd",
            //"they'd",
            //"it'd",
            //"that'd",
            //"who'd",
            //"I'd",
            //"you'd",
            //"he'd",
            //"she'd",
            //"they'd",
            //"it'd",
            //"that'd",
            //"who'd",
            //"I've",
            //"you've",
            //"they've",
            //"we've",
            //"who've",
            //"we're",
            //"they're",
            //"who're",
            //"you're",
            //"he's",
            //"she's",
            //"it's",
            //"that's",
            //"there's",
            //"what's",
            //"where is",
            //"who is",
            //"when is",
            //"why is",
            //"let us",
            //"I am",
            //"where's",
            //"who's",
            //"when's",
            //"why's",
            //"let's",
            //"I'm",
            //"attorney",
            //"been",
            //"beyond",
            //"city",
            //"community",
            //"conversation",
            //"county",
            //"decide",
            //"decision",
            //"estimate",
            //"finance",
            //"financial",
            //"frequent",
            //"govern",
            //"government",
            //"guilt",
            //"guilty",
            //"include",
            //"income",
            //"initial",
            //"innocence",
            //"innocent",
            //"introduce",
            //"introduction",
            //"month",
            //"newspaper",
            //"notice",
            //"office",
            //"official",
            //"procedure",
            //"program"

            //            };


            //            List<string> words = new List<string>{ "I",
            //"a",
            //"able",
            //"about",
            //"above",
            //"act",
            //"add",
            //"after",
            //"again",
            //"against",
            //"age",
            //"ago",
            //"air",
            //"all",
            //"also",
            //"always",
            //"am",
            //"among",
            //"an",
            //"and",
            //"animal",
            //"answer",
            //"any",
            //"appear",
            //"are",
            //"area",
            //"as",
            //"ask",
            //"at",
            //"back",
            //"base",
            //"be",
            //"beauty",
            //"bed",
            //"been",
            //"before",
            //"began",
            //"begin",
            //"behind",
            //"best",
            //"better",
            //"between",
            //"big",
            //"bird",
            //"black",
            //"blue",
            //"boat",
            //"body",
            //"book",
            //"both",
            //"box",
            //"boy",
            //"bring",
            //"brought",
            //"build",
            //"busy",
            //"but",
            //"by",
            //"call",
            //"came",
            //"can",
            //"car",
            //"care",
            //"carry",
            //"cause",
            //"center",
            //"certain",
            //"change",
            //"check",
            //"children",
            //"city",
            //"class",
            //"clear",
            //"close",
            //"cold",
            //"color",
            //"come",
            //"common",
            //"complete",
            //"contain",
            //"correct",
            //"could",
            //"country",
            //"course",
            //"cover",
            //"cross",
            //"cry",
            //"cut",
            //"dark",
            //"day",
            //"decide",
            //"deep",
            //"develop",
            //"did",
            //"differ",
            //"direct",
            //"do",
            //"does",
            //"dog",
            //"don't",
            //"done",
            //"door",
            //"down",
            //"draw",
            //"drive",
            //"dry",
            //"during",
            //"each",
            //"early",
            //"earth",
            //"ease",
            //"east",
            //"eat",
            //"end",
            //"enough",
            //"even",
            //"ever",
            //"every",
            //"example",
            //"eye",
            //"face",
            //"fact",
            //"fall",
            //"family",
            //"far",
            //"farm",
            //"fast",
            //"father",
            //"feel",
            //"feet",
            //"few",
            //"field",
            //"figure",
            //"fill",
            //"final",
            //"find",
            //"fine",
            //"fire",
            //"first",
            //"fish",
            //"five",
            //"fly",
            //"follow",
            //"food",
            //"foot",
            //"for",
            //"force",
            //"form",
            //"found",
            //"four",
            //"free",
            //"friend",
            //"from",
            //"front",
            //"full",
            //"game",
            //"gave",
            //"get",
            //"girl",
            //"give",
            //"go",
            //"gold",
            //"good",
            //"got",
            //"govern",
            //"great",
            //"green",
            //"ground",
            //"group",
            //"grow",
            //"had",
            //"half",
            //"hand",
            //"happen",
            //"hard",
            //"has",
            //"have",
            //"he",
            //"head",
            //"hear",
            //"heard",
            //"heat",
            //"help",
            //"her",
            //"here",
            //"high",
            //"him",
            //"his",
            //"hold",
            //"home",
            //"horse",
            //"hot",
            //"hot",
            //"hour",
            //"house",
            //"how",
            //"hundred",
            //"idea",
            //"if",
            //"in",
            //"inch",
            //"interest",
            //"is",
            //"island",
            //"it",
            //"just",
            //"keep",
            //"kind",
            //"king",
            //"knew",
            //"know",
            //"land",
            //"language",
            //"large",
            //"last",
            //"late",
            //"laugh",
            //"lay",
            //"lead",
            //"learn",
            //"leave",
            //"left",
            //"less",
            //"let",
            //"letter",
            //"life",
            //"light",
            //"like",
            //"line",
            //"list",
            //"listen",
            //"little",
            //"live",
            //"long",
            //"look",
            //"lot",
            //"love",
            //"low",
            //"machine",
            //"made",
            //"main",
            //"make",
            //"man",
            //"many",
            //"map",
            //"mark",
            //"may",
            //"me",
            //"mean",
            //"measure",
            //"men",
            //"might",
            //"mile",
            //"mind",
            //"minute",
            //"miss",
            //"money",
            //"moon",
            //"more",
            //"morning",
            //"most",
            //"mother",
            //"mountain",
            //"move",
            //"much",
            //"music",
            //"must",
            //"my",
            //"name",
            //"near",
            //"need",
            //"never",
            //"new",
            //"next",
            //"night",
            //"no",
            //"north",
            //"note",
            //"nothing",
            //"notice",
            //"noun",
            //"now",
            //"number",
            //"numeral",
            //"object",
            //"of",
            //"off",
            //"often",
            //"oh",
            //"old",
            //"on",
            //"once",
            //"one",
            //"only",
            //"open",
            //"or",
            //"order",
            //"other",
            //"our",
            //"out",
            //"over",
            //"own",
            //"page",
            //"paper",
            //"part",
            //"pass",
            //"pattern",
            //"people",
            //"perhaps",
            //"person",
            //"picture",
            //"piece",
            //"place",
            //"plain",
            //"plan",
            //"plane",
            //"plant",
            //"play",
            //"point",
            //"port",
            //"pose",
            //"possible",
            //"pound",
            //"power",
            //"press",
            //"problem",
            //"produce",
            //"product",
            //"pull",
            //"put",
            //"question",
            //"quick",
            //"rain",
            //"ran",
            //"reach",
            //"read",
            //"ready",
            //"real",
            //"record",
            //"red",
            //"remember",
            //"rest",
            //"right",
            //"river",
            //"road",
            //"rock",
            //"room",
            //"round",
            //"rule",
            //"run",
            //"said",
            //"same",
            //"saw",
            //"say",
            //"school",
            //"science",
            //"sea",
            //"second",
            //"see",
            //"seem",
            //"self",
            //"sentence",
            //"serve",
            //"set",
            //"several",
            //"shape",
            //"she",
            //"ship",
            //"short",
            //"should",
            //"show",
            //"side",
            //"simple",
            //"since",
            //"sing",
            //"sit",
            //"six",
            //"size",
            //"sleep",
            //"slow",
            //"small",
            //"snow",
            //"so",
            //"some",
            //"song",
            //"soon",
            //"sound",
            //"south",
            //"special",
            //"spell",
            //"stand",
            //"star",
            //"start",
            //"state",
            //"stay",
            //"step",
            //"still",
            //"stood",
            //"stop",
            //"story",
            //"street",
            //"strong",
            //"study",
            //"such",
            //"sun",
            //"sure",
            //"surface",
            //"table",
            //"tail",
            //"take",
            //"talk",
            //"teach",
            //"tell",
            //"ten",
            //"test",
            //"than",
            //"that",
            //"the",
            //"their",
            //"them",
            //"then",
            //"there",
            //"these",
            //"they",
            //"thing",
            //"think",
            //"this",
            //"those",
            //"though",
            //"thought",
            //"thousand",
            //"three",
            //"through",
            //"time",
            //"to",
            //"together",
            //"told",
            //"too",
            //"took",
            //"top",
            //"toward",
            //"town",
            //"travel",
            //"tree",
            //"true",
            //"try",
            //"turn",
            //"two",
            //"under",
            //"unit",
            //"until",
            //"up",
            //"us",
            //"use",
            //"usual",
            //"very",
            //"voice",
            //"vowel",
            //"wait",
            //"walk",
            //"want",
            //"war",
            //"warm",
            //"was",
            //"watch",
            //"water",
            //"way",
            //"we",
            //"week",
            //"weight",
            //"well",
            //"went",
            //"were",
            //"west",
            //"what",
            //"wheel",
            //"when",
            //"where",
            //"which",
            //"while",
            //"white",
            //"who",
            //"whole",
            //"why",
            //"will",
            //"wind",
            //"with",
            //"wonder",
            //"wood",
            //"word",
            //"work",
            //"world",
            //"would",
            //"write",
            //"year",
            //"yes",
            //"yet",
            //"you",
            //"young",
            //"your" };


            timer1.Start();
            foreach (string word in words)
            {
                label1.Text = word;


                timeStart = DateTime.Now;

                while (!match)
                {
                    SendKeys.Flush();
                }

                textBox1.Text = "";
                timeEnd = DateTime.Now;
                TimeSpan span1 = timeEnd - timeStart;

                //listBox1.Items.Add(word + " : " + span1.Seconds.ToString() + ":" + span1.Milliseconds.ToString());
                //listBox1.Items.AddRange(new object[] { word,span1.Seconds.ToString() + ":" + span1.Milliseconds.ToString() } );

                //string[] row = {  word, span1.Seconds.ToString() + ":" + span1.Milliseconds.ToString(), mistakes.ToString() } ;
                //ListViewItem item1 = new ListViewItem(row);
                //listView1.Items.Add(item1);

                string time1 = span1.Seconds.ToString("D3") + ":" + span1.Milliseconds.ToString("D3");

                dataGridView1.Rows.Add(word, time1);

                // Test

                match = false;
            }

            MessageBox.Show("Done!");
            timer1.Stop();
        }

        public void Timer_Tick(object sender, EventArgs e)
        {
            //timeLeft--;

            //label1.Text = timeLeft.ToString();

            //if (timeLeft <= 0)
            //{
            //    timer1.Stop();
            //    label1.Show();
            //    button1.Show();
            //}

            if (label1.Text.ToLower().Trim() == textBox1.Text.ToLower().Trim())
            {
                match = true;
            }
            //else
            //{
            //    if (textBox1.Text.Trim() != "")
            //    {
            //        mistakes++;
            //        textBox1.Text = "";
            //    }
            //}
        }
    }
}
