//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class speed
    {
        public int Id { get; set; }
        public int wordid { get; set; }
        public double milliseconds { get; set; }
        public System.DateTime datetime0 { get; set; }
    }
}
